- name: configure the DB server
  hosts: db
  become: yes
  vars:
    login_host: db.rsdevops78s.online
  vars_prompt:
  - name: mysql_root_password
    prompt: please enter MySQL root password
    private: no
  tasks:
  - name: install MySQL server
    ansible.builtin.dnf:
      name: mysql-server
      state: latest

  - name: start and enable MySQL server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: install mysql python dependences
    ansible.builtin.pip:
      name: 
      - PyMySQL
      - cryptography # to get password access have to install
      executable: pip3.9 # based on ansible python version showing have to install python dependency version

  # check the setup password created or not
  - name: check DB connection
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_host: "{{ login_host }}"
      filter: version
    ignore_errors: yes
    register: mysql_connection_output

  - name: print output
    ansible.builtin.debug:
      msg: "Output: {{mysql_connection_output}} "
