- name: configure the DB server
  hosts: localhost
  vars:
    login_host: db.rsdevops78s.online
  become: yes
  tasks: 
  - name: install mysql server    
    ansible.builtin.dnf:
      name: mysql-server
      state: latest

  - name: start and enable the server
    ansible.builtin.service:
      name: mysql-server
      state: started
      enabled: yes

  # check the DB connection and password setup created or not..
  - name: check DB connection
    community.mysql.mysql_info:
      login_user: root
      login_password: ExpenseApp@1
      login_host: "{{ login_host }}"
      filter: version
    ignore_error: yes
    register: mysql_connection_output

  - name: print the output info
    ansible.builtin.debug:
      msg: "Output is: {{ mysql_connection_output }}"
