- name: configure the DB server
  hosts: localhost
  vars:
    login_host: db.rsdevops78s.online
  vars_prompt:
    name: mysql_root_password
    prompt: please enter the root password
    private: no
  become: yes
  tasks: 
  - name: install mysql server    
    ansible.builtin.dnf:
      name: mysql-server
      state: latest

  - name: start and enable the server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: install mysql python dependences
    ansible.builtin.pip:
      name: 
      - PyMySQL
      - cryptography
      executable: pip3.9

  # check the DB connection and password setup created or not..
  - name: check DB connection
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_host: "{{ login_host }}"
      filter: version
    ignore_errors: yes
    register: mysql_connection_output

  - name: print the output info
    ansible.builtin.debug:
      msg: "Output is: {{ mysql_connection_output }}"

  - name: setup mysql root password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ mysql_root_password }}"
    when: mysql_connection_output.failed is true
