- name: configure the db server
  hosts: db
  become: yes
  vars:
    login_host: db.rsdevops78s.online
  vars_prompt:
  - name: mysql_root_password
    prompt: please enter the password
    private: no
    
  tasks:
  - name: install mysql server
    ansible.builtin.dnf:
      name: mysql-server
      state: latest

  - name: start and enable the server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: install mysql python dependences
    ansible.builtin.pip:
      name:
        - PyMySQL
        - cryptography
      executable: pip3.9


  # check the setup password is created or not

  - name: check DB connection
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_host: db.rsdevops78s.online
      filter: version
    ignore_errors: yes
    register: mysql_connection_output

  - name: print the output info
    ansible.builtin.debug:
      msg: "output is: {{ mysql_connection_output }}"

  - name: set mysql_root_password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ login_password }}"
    when: mysql_connection_output.failed is true